version: 1
root-markers:
  - .git/
tools:
  python-flake8: &python-flake8
    lint-command: 'flake8 --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

languages:
  python:
    - <<: *python-flake8

