#!/usr/bin/env bash
set -euo pipefail

# --------------------------------------------------------------------
# This script is used to run the install script in a docker container
# and then run the test script.
#

IMAGE=${IMAGE:-"andrejusk/dotfiles"}
DOCKERFILE=${DOCKERFILE:-Dockerfile}
uuid=$(
    uuidgen 2> /dev/null \
    || cat /proc/sys/kernel/random/uuid 2> /dev/null \
    || echo $RANDOM
)
tag=${TAG:-"$uuid"}

echo "Building $IMAGE:$tag using $DOCKERFILE"

docker build . \
    --build-arg UUID=$uuid \
    --cache-from $IMAGE \
    --tag $IMAGE:$tag \
    --target test \
    -f "$DOCKERFILE"

docker run \
    -v "$(pwd)"/logs:/home/test-user/.dotfiles/logs \
    $IMAGE:$tag
