#!/usr/bin/env bash
set -euo pipefail

# --------------------------------------------------------------------
# This script is used to run the install script in a docker container
# and then run the test script.
#

IMAGE=${IMAGE:-"andrejusk/dotfiles"}
tag=${TAG:-$(cat /proc/sys/kernel/random/uuid)}

docker build . \
    --build-arg UUID=$tag \
    --cache-from $IMAGE \
    --tag $IMAGE:$tag \
    --target test

docker run \
    -v "$(pwd)"/logs:/home/test-user/.dotfiles/logs \
    $IMAGE:$tag
