name: Dotfiles publisher
on:
  push:
    branches:
      - master

jobs:
  publish-installer:
    name: Publish setup script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0

      # Set up the gcloud auth credentials
      - name: 'Set up auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      # Set up the gcloud CLI
      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v1.1.0

      # Publish the setup script
      - name: 'Run publish script'
        run: scripts/publish
