name: Dotfiles publisher
on: [push]
# on:
#   push:
#     branches:
#       - master

jobs:
  publish-installer:
    name: Publish setup script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        name: Publish to CDN
        run: ./scripts/publish.sh
