name: Dotfiles publisher
on: [push]
# on:
#   push:
#     branches:
#       - master

jobs:
  publish-installer:
    name: Publish setup script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true
      - name: Publish to CDN
        run: ./scripts/publish.sh
